// ============================================================
// AudioManager + Bark system + manifest wiring registry.
//
// Every sound is a named event routed through AudioManager.
// Real audio is OPTIONAL drop-in: files placed under assets/audio/
// (vo/ voice notes, music/ tracks, sfx/ event one-shots) and listed
// in assets/audio/index.json (regenerate with `node tools/audio_index.mjs`)
// play automatically; barks always render as text, so the silent
// build keeps working when the folder is empty.
//
// WIRING: call sites obtain their fire function from
// Barks.wire(rowId, where) at module init, so the registry is
// built from real, executed code. Rows referenced from pure data
// (cutscene scripts, level data) are registered by the data
// scanner in main.js. The boot coverage report lists any
// manifest row nobody wired.
// ============================================================

import { CONFIG } from '../config.js';
import { MANIFEST, EVENTS, MUSIC_SLOTS } from '../data/manifest.js';
import { VOICE_ALIASES, MUSIC_ALIASES, SFX_ALIASES } from '../data/audio_map.js';
import { drawText, wrapText, textWidth, LINE_H } from '../engine/font.js';
import { Save } from './save.js';
import { View, roundedRect } from '../engine/render.js';

const rowById = new Map(MANIFEST.map((r) => [r.id, r]));

const AUDIO_EXTS = ['opus', 'ogg', 'mp3', 'm4a', 'wav', 'webm'];
const stemOf = (file) => file.replace(/\.[a-z0-9]+$/i, '');

export const AudioManager = {
  lastEvent: '-',
  started: false,              // true once the player's first gesture unlocked audio
  music: null,                 // current slot id (the jukebox name source of truth)
  menuTrack: 'title',          // track the title/main-menu play; jukebox can repoint it
  knownEvents: new Set(EVENTS),
  files: new Set(),            // uploaded audio paths, from assets/audio/index.json
  cache: new Map(),            // path -> HTMLAudioElement
  ctx: null,                   // shared AudioContext (lets gain exceed 1.0)
  gains: new Map(),            // path -> GainNode (when Web Audio routing succeeds)
  musicEl: null, musicPath: null,
  voiceEl: null, voicePath: null,
  duck: false,   // true while a voice clip is playing; drops music gain

  // Discover uploaded audio. index.json is regenerated by
  // tools/audio_index.mjs; an empty list = the silent build.
  async init() {
    try {
      const r = await fetch('assets/audio/index.json');
      if (r.ok) this.files = new Set((await r.json()).files || []);
    } catch (e) { /* no audio shipped: stay silent */ }
    // warm the cache for event one-shots (sfx/<event>) so the first hit —
    // e.g. the death sting — fires instantly instead of fetching on play.
    for (const ev of EVENTS) {
      const p = this.aliasPath(SFX_ALIASES[ev]) || this.resolve('sfx/' + ev);
      if (p) this.prepare(p, false).load();
    }
    // browsers gate audio behind a user gesture: resume the graph and
    // (re)start music on the FIRST interaction of any kind (key, click, tap,
    // pointer) so menu music kicks in the instant the player touches the page.
    // ctx.resume() is async — chain startMusic so it fires once running.
    const GESTURES = ['keydown', 'pointerdown', 'mousedown', 'touchstart', 'click'];
    const kick = () => {
      this.started = true;
      for (const g of GESTURES) window.removeEventListener(g, kick);
      const resume = this.ctx && this.ctx.state === 'suspended'
        ? this.ctx.resume()
        : Promise.resolve();
      resume.then(() => { if (this.music) this.startMusic(this.music); });
    };
    for (const g of GESTURES) window.addEventListener(g, kick, { once: true });
  },

  resolve(stem) {
    for (const ext of AUDIO_EXTS) {
      if (this.files.has(stem + '.' + ext)) return 'assets/audio/' + stem + '.' + ext;
    }
    return null;
  },

  // An explicit alias is a full relative path already (with extension).
  aliasPath(rel) {
    return rel && this.files.has(rel) ? 'assets/audio/' + rel : null;
  },

  // settings dials are 0-10; kind is 'music' | 'voice' | null (master only)
  vol(kind) {
    const s = Save.data.settings;
    if (s.muted) return 0;
    return Math.max(0, Math.min(1, (s.master / 10) * (kind ? s[kind] / 10 : 1)));
  },

  // per-channel boost layered on the slider; >1 makes a channel punch above
  // the source level (only audible through the Web Audio graph).
  boost(kind) {
    return kind === 'music' ? CONFIG.audio.musicGain : CONFIG.audio.sfxGain;
  },

  // Route an element through master -> GainNode -> destination once, so its
  // level can exceed 1.0. Falls back to plain el.volume if Web Audio is absent.
  route(el, path) {
    if (!this.ctx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return;
      try { this.ctx = new AC(); } catch (e) { this.ctx = null; return; }
    }
    try {
      const src = this.ctx.createMediaElementSource(el); // same-origin: no CORS
      const g = this.ctx.createGain();
      src.connect(g); g.connect(this.ctx.destination);
      this.gains.set(path, g);
    } catch (e) { /* routing failed: el.volume (capped at 1) still plays */ }
  },

  setLevel(path, el, kind, mul = 1) {
    const g = this.gains.get(path);
    const duckMul = (kind === 'music' && this.duck) ? 0.55 : 1.0;
    const level = this.vol(kind) * this.boost(kind) * duckMul * mul;
    if (g) { el.volume = 1; g.gain.value = level; }   // graph handles >1
    else { el.volume = Math.min(1, level); }           // fallback ceiling
  },

  prepare(path, loop) {
    let el = this.cache.get(path);
    if (!el) {
      el = new Audio(encodeURI(path)); // names have spaces / ! / '
      el.preload = 'auto';             // start buffering before first play
      this.cache.set(path, el);
      this.route(el, path);
    }
    el.loop = loop;
    return el;
  },

  playFile(path, kind, mul = 1) {
    const el = this.prepare(path, false);
    this.setLevel(path, el, kind, mul);
    el.currentTime = 0;
    const resume = this.ctx && this.ctx.state === 'suspended' ? this.ctx.resume() : Promise.resolve();
    resume.then(() => el.play().catch(() => {}));
    return el;
  },

  // Named event. Logs always; if the user dropped sfx/<event>.opus
  // (or any supported extension), it plays too.
  play(event, detail = '') {
    this.lastEvent = event + (detail ? ':' + detail : '');
    const p = this.aliasPath(SFX_ALIASES[event]) || this.resolve('sfx/' + event);
    if (p) this.playFile(p, 'voice', CONFIG.audio.eventGain[event] || 1);
  },

  // A Vaks voice note for a manifest row. Variant pools may ship one
  // file per line (vo/<stem>_2.opus = line index 1); a single
  // vo/<stem>.opus covers every variant. One mouth: lets current clip
  // finish before starting the next one. Ducks music while playing.
  voice(row, lineIdx, interrupt = false) {
    if (this.voiceEl && !this.voiceEl.paused && !this.voiceEl.ended) {
      if (!interrupt) return;       // one mouth: let the current line finish
      this.voiceEl.pause();         // ...unless this one barges in (the meow)
    }
    const alias = VOICE_ALIASES[row.id];
    let p = null;
    if (Array.isArray(alias)) p = this.aliasPath(alias[lineIdx]) || this.aliasPath(alias.find(Boolean));
    else if (alias) p = this.aliasPath(alias);
    if (!p) { // no alias: try the vo/<stem> convention
      const stem = stemOf(row.file);
      p = this.resolve(stem + '_' + (lineIdx + 1)) || this.resolve(stem);
    }
    if (!p) return;
    this.duck = true;
    if (this.musicEl && this.musicPath) this.setLevel(this.musicPath, this.musicEl, 'music');
    this.voicePath = p;
    this.voiceEl = this.playFile(p, 'voice');
    this.voiceEl.addEventListener('ended', () => {
      this.duck = false;
      if (this.musicEl && this.musicPath) this.setLevel(this.musicPath, this.musicEl, 'music');
    }, { once: true });
  },

  playMusic(slotId) {
    this.music = slotId;
    this.lastEvent = 'music:' + slotId;
    this.startMusic(slotId);
  },

  startMusic(slotId) {
    const slot = MUSIC_SLOTS.find((m) => m.id === slotId);
    const p = this.aliasPath(MUSIC_ALIASES[slotId]) || (slot && this.resolve(stemOf(slot.file)));
    if (!p) { // slot named but no track uploaded: silence, name still shows
      if (this.musicEl) this.musicEl.pause();
      this.musicEl = null; this.musicPath = null;
      return;
    }
    if (this.musicPath === p && this.musicEl && !this.musicEl.paused) return; // already spinning
    if (this.musicEl && this.musicPath !== p) this.musicEl.pause();
    const el = this.prepare(p, true);
    this.musicEl = el; this.musicPath = p;
    this.setLevel(p, el, 'music');
    const resume = this.ctx && this.ctx.state === 'suspended' ? this.ctx.resume() : Promise.resolve();
    resume.then(() => el.play().catch(() => {}));
  },

  // stop the current track (death/level-clear cut the music so the
  // sting lands in silence). Music resumes when a slot is played again.
  stopMusic() {
    if (this.musicEl) this.musicEl.pause();
    this.musicEl = null;
    this.musicPath = null;
  },

  // Hold the current track in place (keeps the element + position so it can
  // pick up exactly where it left off) — used to freeze the world while Vaks
  // skins up. resumeMusic() plays it again from the same spot.
  pauseMusic() {
    if (this.musicEl) this.musicEl.pause();
  },
  resumeMusic() {
    if (!this.musicEl || !this.musicPath || !this.musicEl.paused) return;
    const resume = this.ctx && this.ctx.state === 'suspended' ? this.ctx.resume() : Promise.resolve();
    resume.then(() => this.musicEl.play().catch(() => {}));
  },

  stopVoice() {
    if (this.voiceEl) {
      this.voiceEl.pause();
      this.voiceEl.currentTime = 0;
    }
    this.duck = false;
    if (this.musicEl && this.musicPath) this.setLevel(this.musicPath, this.musicEl, 'music');
  },

  // live re-apply when the settings sliders move
  applyVolumes() {
    if (this.musicEl && this.musicPath) this.setLevel(this.musicPath, this.musicEl, 'music');
    if (this.voiceEl && this.voicePath) this.setLevel(this.voicePath, this.voiceEl, 'voice');
  },

  // is a music track actually audible right now? (element exists, not paused/ended)
  musicPlaying() {
    return !!(this.musicEl && !this.musicEl.paused && !this.musicEl.ended);
  },

  musicName(slotId) {
    const s = MUSIC_SLOTS.find((m) => m.id === slotId);
    return s ? s.name : '';
  },
};

// ---------------- bark system ----------------

const wired = new Map();      // rowId -> where (call site description)
const firedRows = new Set();  // rowIds actually fired this session
const cooldowns = new Map();  // key -> time remaining
const lastLine = new Map();   // rowId -> last variant index

export const Barks = {
  bubbles: [],   // { text, shown, anchor, t, hold, done }
  subtitle: null, // { text, shown, t, hold, speaker }

  wire(rowId, where) {
    if (!rowById.has(rowId)) throw new Error('Unknown manifest row: ' + rowId);
    if (!wired.has(rowId)) wired.set(rowId, where);
    return (opts) => this.fire(rowId, opts);
  },

  wireData(rowId, where) {
    if (!rowById.has(rowId)) throw new Error('Unknown manifest row: ' + rowId);
    if (!wired.has(rowId)) wired.set(rowId, where);
  },

  pickIndex(row, idx) {
    if (idx !== undefined) { lastLine.set(row.id, idx); return idx; }
    if (row.lines.length === 1) return 0;
    let i = Math.floor(Math.random() * row.lines.length);
    if (i === lastLine.get(row.id)) i = (i + 1) % row.lines.length;
    lastLine.set(row.id, i);
    return i;
  },

  pickLine(row, idx) { return row.lines[this.pickIndex(row, idx)]; },

  // opts: { anchor, line, event, force, subtitle, speaker }
  fire(rowId, opts = {}) {
    const row = rowById.get(rowId);
    const event = opts.event || row.event;
    if (!opts.force) {
      const cd = cooldowns.get(rowId) || 0;
      const ecd = cooldowns.get('ev:' + event) || 0;
      if (cd > 0 || ecd > 0) return false;
    }
    const rowCd = CONFIG.barks.cooldown[event] !== undefined
      ? CONFIG.barks.cooldown[event] : CONFIG.barks.defaultCooldown;
    cooldowns.set(rowId, rowCd);
    cooldowns.set('ev:' + event, Math.min(rowCd, 2.5));
    firedRows.add(rowId);
    AudioManager.play(event, rowId);
    const li = this.pickIndex(row, opts.line);
    AudioManager.voice(row, li, opts.interrupt);
    const text = row.lines[li];
    if (opts.anchor && !opts.subtitle) {
      // one bubble per anchor: replace
      this.bubbles = this.bubbles.filter((b) => b.anchor !== opts.anchor);
      this.bubbles.push({ text, anchor: opts.anchor, t: 0, shown: 0 });
    } else {
      this.subtitle = { text, t: 0, shown: 0, speaker: opts.speaker || '' };
    }
    return true;
  },

  // Instructional / narrator text (not a voice line): subtitle only.
  note(text, speaker = '') {
    this.subtitle = { text, t: 0, shown: 0, speaker };
  },

  // Cutscene dialogue: fires the row's event + returns the text,
  // rendering is the cutscene player's typewriter box.
  quote(rowId, idx) {
    const row = rowById.get(rowId);
    firedRows.add(rowId);
    AudioManager.play(row.event, rowId);
    const li = this.pickIndex(row, idx);
    AudioManager.voice(row, li);
    return row.lines[li];
  },

  cps() { return CONFIG.barks.charsPerSec[Save.data.settings.textSpeed] || 26; },

  holdFor(text) { return CONFIG.barks.holdBase + text.length * CONFIG.barks.holdPerChar; },

  update(dt) {
    for (const [k, v] of cooldowns) {
      if (v > 0) cooldowns.set(k, v - dt);
    }
    const cps = this.cps();
    for (let i = this.bubbles.length - 1; i >= 0; i--) {
      const b = this.bubbles[i];
      b.t += dt;
      b.shown = Math.min(b.text.length, b.shown + cps * dt);
      if (b.shown >= b.text.length && b.t > b.text.length / cps + this.holdFor(b.text)) {
        this.bubbles.splice(i, 1);
      }
    }
    if (this.subtitle) {
      const s = this.subtitle;
      s.t += dt;
      s.shown = Math.min(s.text.length, s.shown + cps * dt);
      if (s.shown >= s.text.length && s.t > s.text.length / cps + this.holdFor(s.text)) {
        this.subtitle = null;
      }
    }
  },

  clear() { this.bubbles = []; this.subtitle = null; },

  // Bubbles: screen space, anchored to world entities via camera.
  draw(ctx, cam) {
    for (const b of this.bubbles) {
      const a = b.anchor;
      const ax = cam ? a.x - cam.ox() : a.x;
      const ay = cam ? (a.y - (a.bubbleH || 26)) - cam.oy() : a.y - (a.bubbleH || 26);
      if (ax < -40 || ax > View.w + 40 || ay < -60 || ay > View.h + 40) continue;
      this.drawBubble(ctx, b, ax, ay);
    }
    if (this.subtitle) this.drawSubtitle(ctx, this.subtitle);
  },

  drawBubble(ctx, b, ax, ay) {
    const text = b.text.slice(0, Math.ceil(b.shown));
    const lines = wrapText(b.text, CONFIG.barks.bubbleMaxW);
    let w = 0;
    for (const l of lines) w = Math.max(w, textWidth(l));
    w += 8;
    const h = lines.length * LINE_H + 5;
    let x = Math.round(ax - w / 2);
    x = Math.max(2, Math.min(View.w - w - 2, x));
    let y = Math.round(ay - h - 6);
    y = Math.max(2, y);
    roundedRect(ctx, x - 1, y - 1, w + 2, h + 2, '#2a2438');
    roundedRect(ctx, x, y, w, h, '#fdf6e0');
    // tail
    const tx = Math.max(x + 3, Math.min(x + w - 6, Math.round(ax) - 2));
    ctx.fillStyle = '#fdf6e0';
    ctx.fillRect(tx, y + h, 4, 2);
    ctx.fillRect(tx + 1, y + h + 2, 2, 2);
    let used = 0;
    for (let i = 0; i < lines.length; i++) {
      const remain = text.length - used;
      if (remain <= 0) break;
      const part = lines[i].slice(0, remain);
      drawText(ctx, part, x + 4, y + 3 + i * LINE_H, { color: '#2a2438' });
      used += lines[i].length + 1;
    }
  },

  drawSubtitle(ctx, s) {
    const text = s.text.slice(0, Math.ceil(s.shown));
    const full = (s.speaker ? s.speaker + ': ' : '') + s.text;
    const lines = wrapText(full, View.w - 60);
    const h = lines.length * LINE_H + 8;
    const y = View.h - h;
    ctx.fillStyle = 'rgba(8,8,16,0.82)';
    ctx.fillRect(0, y, View.w, h);
    ctx.fillStyle = '#8ae08a';
    ctx.fillRect(0, y, View.w, 1);

    const shownFull = (s.speaker ? s.speaker + ': ' : '') + text;
    let used = 0;
    for (let i = 0; i < lines.length; i++) {
      const remain = shownFull.length - used;
      if (remain <= 0) break;
      drawText(ctx, lines[i].slice(0, remain), View.w / 2, y + 5 + i * LINE_H,
        { color: '#f4f0e0', align: 'center' });
      used += lines[i].length + 1;
    }
  },
};

// ---------------- coverage report ----------------

export function coverageReport() {
  const unwired = [];
  for (const row of MANIFEST) {
    if (!wired.has(row.id)) unwired.push(row.id);
  }
  const lines = [];
  lines.push(`[VAK'S CAVE] MANIFEST COVERAGE: ${MANIFEST.length - unwired.length}/${MANIFEST.length} rows wired, ${unwired.length} unwired.`);
  if (unwired.length) {
    for (const id of unwired) lines.push(`  UNWIRED: ${id} ("${rowById.get(id).trigger}")`);
  }
  return { lines, unwired, wired };
}

export function wiringTable() {
  const out = [];
  for (const row of MANIFEST) {
    out.push(`  ${row.id.padEnd(18)} -> ${(wired.get(row.id) || 'UNWIRED').padEnd(34)} | ${row.trigger}`);
  }
  return out;
}

export function firedReport() { return firedRows; }
